version: '3'
services:
  master:
    # container_name: ros-master
    environment:
      - ROS_MASTER_URI=http://localhost:11311
    build:
      context: ./master
    ports:
      - "11311:11311"
  talker:
    # container_name: ros-node
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_HOSTNAME=talker
    build:
      context: ./node
    depends_on:
      - master
  listener:
    # container_name: ros-node
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_HOSTNAME=listener
    build:
      context: ./node
    depends_on:
      - master
