version: '3'
services:
  master:
    # container_name: ros-master
    build:
      context: ./master
    ports:
      - "11311:11311"
  node:
    # container_name: ros-node
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_HOSTNAME=node
    build:
      context: ./node
    depends_on:
      - master
