version: '3'
services:
  master:
    # container_name: ros-master
    build:
      context: ./master
    ports:
      - "11311:11311"
  talker:
    # container_name: ros-node
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_HOSTNAME=talker
    build:
      context: ./node
    entrypoint: ["/usr/local/bin/wait-for-it.sh", "master:11311", "--", "/usr/local/bin/entrypoint.sh", "rostopic", "pub", "-r", "1", "chatter", "std_msgs/String", "Hello, world"]
    depends_on:
      - master
  listener:
    # container_name: ros-node
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_HOSTNAME=listener
    build:
      context: ./node
    entrypoint: ["/usr/local/bin/wait-for-it.sh", "master:11311", "--", "/usr/local/bin/entrypoint.sh", "rostopic", "echo", "chatter"]
    depends_on:
      - master
